# Homework assignment #2 - NumPy

Name: Aleksandra Olshanova

ID:728945613

### Import NumPy Package

In [31]:
# import numpy package
import numpy as np

### 1. Basic Data Statistics

####  Create an array of 5 zeros

In [32]:
a = np.zeros((5, 1), float)
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

array([0., 0., 0., 0., 0.])

#### Use this array to create an array of 10 fives

In [33]:
b = np.full_like(a, 5.0)
np.vstack([b, b])

array([[5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.]])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Creat the matrix bellow. The code must not use the same function more then one time in one run
 

In [34]:
c = np.zeros((5, 5))
for i in range(c.shape[1]):
 c[:,i] = i
c

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Create a 8x8 matrix and fill it with a checkerboard pattern with 0 zeros and ones.

In [35]:
d = np.zeros((8, 8))
d[::2, 1::2] = 1
d[1::2, ::2] = 1
d

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [36]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Working with data:

# Daily Rate of Growth of new COVID19 Cases in Israel

Read the header row (first row) of file 'covid19_israel.csv', and print the header.

In [37]:
a=np.loadtxt(r"COVID19_Israel.csv", delimiter=",", max_rows=1, dtype='str')
a
#ObservationDate,New Confirmed,New Deaths,New Recovered

array(['ObservationDate', 'New Confirmed', 'New Deaths', 'New Recovered'],
      dtype='<U15')

['ObservationDate' 'New Confirmed' 'New Deaths' 'New Recovered']


Read columns 2, 3, 4 (indices 1, 2, 3) of file "covid19_israel.csv" into **new_cases** variable.  
Use **delimiter** parameter to indicate comma separated values.  
Use **skiprows** parameter to skip the first header row.  
Use **usecols** parameter to read the columns 2, 3, 4 (indices 1, 2, 3).    
Print the last 5 rows.

In [38]:
new_cases=np.loadtxt(r"COVID19_Israel.csv", delimiter=",",skiprows=1, usecols=[1,2,3], dtype='int')
new_cases[-5:,:]

array([[342,   4,  11],
       [584,   0,  10],
       [628,   3,  43],
       [448,   1,  29],
       [663,   4,  63]])

In [12]:
# new_cases = np.loadtxt...


array([[342,   4,  11],
       [584,   0,  10],
       [628,   3,  43],
       [448,   1,  29],
       [663,   4,  63]])

Print the date of the day were the most patients verified.

In [40]:
covid_data= np.loadtxt(r"COVID19_Israel.csv", delimiter=",",skiprows=1, dtype='str')
# ObservationDate,New Confirmed,New Deaths,New Recovered
max_confirmed=np.max(covid_data[:,1].astype(int))
date= [covid_data[:,0][covid_data[:,1] == str(max_confirmed)]]
print('the date of the day were the most patients verified:' , date[0])

the date of the day were the most patients verified: ['3/31/2020']


3/30/2020


Calculate the total daily number of confirmed caases, death cases, and recovered cases using numpy's **cumsum** function.  
Use the correct **axis** parameter to sum across rows.  
Print the total daily number of confirmed cases, death cases, and recovered cases at the last measured date 31/3/2020 on the last row.   

In [41]:
#covid_data= np.loadtxt(r"COVID19_Israel.csv", delimiter=",",skiprows=1, dtype='str')
daily_number = np.cumsum(covid_data[:,1:].astype(int), axis=0)
daily_number[-1]

array([5358,   20,  224])

array([5358,   20,  224])

Calculate the increase in the number of verified cases for each day:<br>
New Confirmed - (New Deaths + New Recovered)<br>
 to new numpy array.

In [21]:
#covid_data= np.loadtxt(r"COVID19_Israel.csv", delimiter=",",skiprows=1, dtype='str')
cdr=covid_data[:,1:]
incr_data = np.zeros((40, 1), float)
for i in range(cdr.shape[0]):
 incr_data[i,0] = int(cdr[i,0]) - (int(cdr[i,1]) + int(cdr[i,2]))
incr_data


array([[  1.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  1.],
       [  0.],
       [  1.],
       [  3.],
       [  3.],
       [  0.],
       [  2.],
       [  3.],
       [  1.],
       [  4.],
       [  0.],
       [ 18.],
       [  0.],
       [ 17.],
       [ 51.],
       [ 22.],
       [ 30.],
       [ 32.],
       [ 58.],
       [  4.],
       [ 75.],
       [ 96.],
       [244.],
       [ 25.],
       [155.],
       [187.],
       [367.],
       [474.],
       [432.],
       [311.],
       [327.],
       [574.],
       [582.],
       [418.],
       [596.]])

Draw a random row from the table and print it.

In [47]:
np.random.seed(42)

In [48]:
random_row_ind = np.random.choice(covid_data.shape[0], size=1)
random_row = covid_data[random_row_ind, :]
print(random_row)

[['3/30/2020' '448' '1' '29']]
