# Homework assignment #2 - NumPy
Name:


ID:

### Import NumPy Package

In [3]:
# import numpy package


### 1. Basic Data Statistics

####  Create an array of 5 zeros

array([0., 0., 0., 0., 0.])

#### Use this array to create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Creat the matrix bellow. The code must not use the same function more then one time in one run
 

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Create a 8x8 matrix and fill it with a checkerboard pattern with 0 zeros and ones.

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Create an array of 20 linearly spaced points between 0 and 1:

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Working with data:

# Daily Rate of Growth of new COVID19 Cases in Israel

Read the header row (first row) of file 'covid19_israel.csv', and print the header.  

['ObservationDate' 'New Confirmed' 'New Deaths' 'New Recovered']


Read columns 2, 3, 4 (indices 1, 2, 3) of file "covid19_israel.csv" into **new_cases** variable.  
Use **delimiter** parameter to indicate comma separated values.  
Use **skiprows** parameter to skip the first header row.  
Use **usecols** parameter to read the columns 2, 3, 4 (indices 1, 2, 3).    
Print the last 5 rows.

In [12]:
# new_cases = np.loadtxt...


array([[342,   4,  11],
       [584,   0,  10],
       [628,   3,  43],
       [448,   1,  29],
       [663,   4,  63]])

Print the date of the day were the most patients verified.

3/30/2020


Calculate the total daily number of confirmed caases, death cases, and recovered cases using numpy's **cumsum** function.  
Use the correct **axis** parameter to sum across rows.  
Print the total daily number of confirmed cases, death cases, and recovered cases at the last measured date 31/3/2020 on the last row.   

array([5358,   20,  224])

In [ ]:
Calculate the increase in the number of verified cases for each day:<br>
New Confirmed - (New Deaths + New Recovered)<br>
 to new numpy array.

array([  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,   3.,   3.,   0.,
         2.,   3.,   1.,   4.,   0.,  18.,   0.,  17.,  51.,  22.,  30.,
        32.,  58.,   4.,  75.,  96., 244.,  25., 155., 187., 367., 474.,
       432., 311., 327., 574., 582., 418., 596.])

Draw a random row from the table and print it.

In [ ]:
np.random.seed(42)

array(['3/30/2020', '448', '1', '29'], dtype='<U9')