# Homework Assignment - 1 Basic

**The main topics we learned in Exe_1:**

**Slicing, Dictionary, List ,Tuples, Nesting Lists, Set, Function,Map, reduce, filter, lambda**

**1.** *Write a Python program to print out a sequence containing all the Chemical elements from Element_list_1 which are not present in Element_list_2.:*

In the first cell, use set() function, In the second use lambda and Filter Functions.


In [1]:
Element_list_1 = ["Hydrogen","Helium","Oxygen","Carbon","Neon","Iron"]
Element_list_2 = ["Neon","Nitrogen", "Silicon","Magnesium","Sulfur","Helium","Hydrogen"]
                     
#Expected Output :
#['Carbon', 'Iron', 'Oxygen']

In [2]:
#Use set()
x = set(Element_list_1)
y = set(Element_list_2)
print(list(x.difference(y)))

['Oxygen', 'Iron', 'Carbon']


In [3]:
# Use lambda & filter()
filter_result = list(filter(lambda x: x not in Element_list_2, Element_list_1))
print(filter_result)

['Oxygen', 'Carbon', 'Iron']


**2.** *Write a Python program that accepts six numbers as input and sorts them in descending order.*

Example:

Input six integers:
15 30 25 14 35 40

After sorting the said integers:
40 35 30 25 15 14

In [7]:
lst = (input().split())
var_lst = list(map(lambda x: int(x), lst))
var_lst.sort(reverse=True)
var_lst

[40, 35, 30, 25, 15, 14]

**3.** *Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings.*


Sample List : ['abc', 'xyz', 'aba', '1221','AbGADA']

Expected Result : 3

In [8]:
list_letters = ['abc', 'xyz', 'aba', '1221','AbGADA']
len(list(filter(lambda x : len(x)>=2 and x[0]==x[-1], list_letters)))

3

**4.** *Write a Python program to sort a given matrix in ascending order according to the sum of its rows.*

Example: (use one of them to try the program on)<br>
Original Matrix:<br>
[[1, 9, 0],<br>
[2, 8, 1],<br>
[1, 1, 1]]<br>

Sort the said matrix in ascending order according to the sum of its rows

[[1, 1, 1],<br>
[1, 9, 0],<br>
[2, 8, 1]]<br>

Original Matrix:<br>
[[1, 9, 0],<br>
[1, -1, 1],<br>
[-2, 4, -5]]<br>

Sort the said matrix in ascending order according to the sum of its rows

[[-2, 4, -5],<br>
[1, -1, 1],<br>
[1, 9, 0]]<br>

In [10]:
import numpy as np
mat = np.array([[1, 9, 0], [2, 8, 1],[1, 1, 1]], float)
first_raw_sum= sum(list(mat[0]))
second_raw_sum= sum(list(mat[1]))
third_raw_sum= sum(list(mat[2]))
if first_raw_sum < second_raw_sum and first_raw_sum < third_raw_sum :
    mat1 = [mat[0]]
    if second_raw_sum < third_raw_sum :
        mat1.append(mat[1])
        mat1.append(mat[2])
        print(np.array(mat1, float))
    else:
        mat1.append(mat[2])
        mat1.append(mat[1])
        print(np.array(mat1, float))
elif second_raw_sum < first_raw_sum and second_raw_sum < third_raw_sum :
    mat1 = [mat[1]]
    if first_raw_sum < third_raw_sum :
        mat1.append(mat[0])
        mat1.append(mat[2])
        print(np.array(mat1, float))
    else:
        mat1.append(mat[2])
        mat1.append(mat[0])
        print(np.array(mat1, float))
elif third_raw_sum < first_raw_sum and third_raw_sum  < second_raw_sum :
    mat1 = [mat[2]]
    if first_raw_sum < second_raw_sum :
        mat1.append(mat[0])
        mat1.append(mat[1])
        print(np.array(mat1, float))
    else:
        mat1.append(mat[1])
        mat1.append(mat[0])
        print(np.array(mat1, float))
else:
    print("I don't know")

#print("first raw:", first_raw_sum, "second raw:",  second_raw_sum, "third raw:",  third_raw_sum )
mat

[[1. 1. 1.]
 [1. 9. 0.]
 [2. 8. 1.]]


array([[1., 9., 0.],
       [2., 8., 1.],
       [1., 1., 1.]])

**5.** *Write a Python program to combine two dictionary adding values for common keys.*
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
Sample output: Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})

Hint: from collections import Counter

In [11]:
from collections import Counter
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
c = Counter(d1) + Counter(d2)
c

Counter({'a': 400, 'b': 400, 'c': 300, 'd': 400})

**6.** Write a Python program that recieve dictionary of elements to their molar weight, and then print the names of the elements with the highest and lowest molar weight.

Sample Output:
Original dictionary elements:

Chemical_elements = {'Scandium': 21, 'Cobalt': 27, 'Sulfur': 16,'Silver': 47 }

Finds the key of the maximum and minimum value of the said dictionary:

Highest Mw: Silver

Lowest Mw: Sulfur



In [1]:
Chemical_elements = {'Scandium': 21, 'Cobalt': 27, 'Sulfur': 16,'Silver': 47 }
Highest_Mw = max(Chemical_elements.values())
Lowest_Mw = min(Chemical_elements.values())
for key, value in Chemical_elements.items():
    if value == Highest_Mw :
        print("Highest Mw:", key)
for key, value in Chemical_elements.items():
    if value == Lowest_Mw:
        print("Lowest_Mw:", key)

Highest Mw: Silver
Lowest_Mw: Sulfur


**7.** *Write a function that recieve two given tuples and return their subtraction using map and lambda.*

Original tuples:
(8,10,3)
(-1,7,9)

Result: after substracting two tuples
(9, 3, -6)

In [13]:
a= (8,10,3)
b=(-1,7,9)
print(tuple(map(lambda x, y: x-y, a, b)))

(9, 3, -6)


**8.** *Write a Python program to compute the product of all the elements of each tuple stored inside a list of tuples.*

Original list of tuples:
[(1, 2), (2, 3), (3, 4)]

Product of all the elements of each tuple stored inside the said list of tuples:
[2, 6, 12]

Original list of tuples:
[(1, 2, 6), (2, 3, -6), (3, 4), (2, 2, 2, 2)]

Product of all the elements of each tuple stored inside the said list of tuples:
[12, -36, 12, 16]

In [14]:
list1 = [(1, 2, 6), (2, 3, -6), (3, 4), (2, 2, 2, 2)]
def mul1(x):
    mulll=1
    for item in x:
        mulll = mulll*item
    return mulll
print(list(map(mul1,list1)))

[12, -36, 12, 16]
