Pandas

In [138]:
import pandas as pd

In [19]:
pd.__version__ # версия панды

'1.4.4'

In [20]:
data = pd.Series([0.25, 0.5, 0.75, 1.0]) #from list
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [21]:
data.values #array of these values

array([0.25, 0.5 , 0.75, 1.  ])

In [22]:
type(data.values)

numpy.ndarray

In [23]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
type(data.index)

pandas.core.indexes.range.RangeIndex

In [25]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [26]:
data['b']

0.5

Dictionaries vs Pandas

In [27]:
bandgap_dict = {'Hg0.7Cd0.3Te':0.35, 'CuBr':3.08,'LuP':1.30, 'Cu3SbSe4':0.40, 'ZnO':3.44} # Dict
bandgap_dict

{'Hg0.7Cd0.3Te': 0.35, 'CuBr': 3.08, 'LuP': 1.3, 'Cu3SbSe4': 0.4, 'ZnO': 3.44}

In [28]:
bandgaps = pd.Series(bandgap_dict) # Pandas
bandgaps

Hg0.7Cd0.3Te    0.35
CuBr            3.08
LuP             1.30
Cu3SbSe4        0.40
ZnO             3.44
dtype: float64

Accessing data with Pandas

In [29]:
bandgaps['CuBr']

3.08

In [30]:
bandgaps['LuP':'ZnO']

LuP         1.30
Cu3SbSe4    0.40
ZnO         3.44
dtype: float64

Series creation: pd.Series(data, index=index)

In [31]:
pd.Series([2, 4, 6]) # list or NumPy array

0    2
1    4
2    6
dtype: int64

In [32]:
pd.Series(5, index=[100, 200, 300]) # repeated scalar

100    5
200    5
300    5
dtype: int64

In [33]:
pd.Series({2:'a', 1:'b', 3:'c'}) # dictionary

2    a
1    b
3    c
dtype: object

In [34]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2]) #access to indexes 3 and 2

3    c
2    a
dtype: object

In [35]:
l = pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 1, 2]) # index change, index field is more important!
l

3    c
1    b
2    a
dtype: object

In [36]:
p=pd.Series([6, 4, 60], index=[-1,50,6])
p

-1      6
 50     4
 6     60
dtype: int64

In [37]:
p.sort_values(ascending=True) #Sort p according to values

 50     4
-1      6
 6     60
dtype: int64

In [38]:
p.sort_index(ascending=True) #Sort p according to index

-1      6
 6     60
 50     4
dtype: int64

Exercise

create a pandas series of 50 random numbers between 0-9 and calculate the frequency counts using the Pandas function 'value_counts()'. Print the frequency counts in sorted order (by value).

In [39]:
import numpy as np
data_of_random_numbers=pd.Series(np.random.randint(0, 10, size=(50)))
data_of_random_numbers

0     3
1     0
2     9
3     2
4     6
5     6
6     4
7     6
8     7
9     0
10    8
11    0
12    1
13    0
14    6
15    8
16    3
17    9
18    4
19    6
20    6
21    1
22    2
23    9
24    2
25    7
26    3
27    1
28    3
29    4
30    4
31    6
32    7
33    4
34    1
35    6
36    6
37    6
38    6
39    6
40    1
41    3
42    4
43    2
44    8
45    4
46    6
47    1
48    3
49    9
dtype: int64

In [40]:
frequency_of_data = data_of_random_numbers.value_counts()
frequency_of_data

6    13
4     7
3     6
1     6
0     4
9     4
2     4
7     3
8     3
dtype: int64

In [41]:
frequency_of_data.sort_values(ascending=True)

7     3
8     3
0     4
9     4
2     4
3     6
1     6
4     7
6    13
dtype: int64

Dataframes

In [65]:
bandgap_dict = {'Hg0.7Cd0.3Te':0.35, 'CuBr':3.08, 'LuP':1.30, 'Cu3SbSe4':0.40, 'ZnO':3.44}
bandgaps = pd.Series(bandgap_dict)
bandgaps

Hg0.7Cd0.3Te    0.35
CuBr            3.08
LuP             1.30
Cu3SbSe4        0.40
ZnO             3.44
dtype: float64

In [66]:
is_metal_dict = {'Hg0.7Cd0.3Te':'', 'CuBr':False, 'LuP':False, 'Cu3SbSe4':False, 'ZnO':False}
is_metal = pd.Series(is_metal_dict)
is_metal

Hg0.7Cd0.3Te         
CuBr            False
LuP             False
Cu3SbSe4        False
ZnO             False
dtype: object

In [44]:
materials = pd.DataFrame({'bandgap':bandgaps, 'is_metal':is_metal})
materials

bandgap is_metal
Hg0.7Cd0.3Te     0.35         
CuBr             3.08    False
LuP              1.30    False
Cu3SbSe4         0.40    False
ZnO              3.44    False

In [45]:
materials.index

Index(['Hg0.7Cd0.3Te', 'CuBr', 'LuP', 'Cu3SbSe4', 'ZnO'], dtype='object')

In [46]:
materials.columns

Index(['bandgap', 'is_metal'], dtype='object')

In [67]:
materials['bandgap']

Hg0.7Cd0.3Te    0.35
CuBr            3.08
LuP             1.30
Cu3SbSe4        0.40
ZnO             3.44
Name: bandgap, dtype: float64

Dataframe creation

In [68]:
 bandgaps # Series

Hg0.7Cd0.3Te    0.35
CuBr            3.08
LuP             1.30
Cu3SbSe4        0.40
ZnO             3.44
dtype: float64

In [49]:
type(bandgaps)

pandas.core.series.Series

In [50]:
dataframe = pd.DataFrame(bandgaps, columns=['bandgap']) # columns - имя столбиков
type(dataframe)

pandas.core.frame.DataFrame

In [51]:
dataframe # DataFrame

bandgap
Hg0.7Cd0.3Te     0.35
CuBr             3.08
LuP              1.30
Cu3SbSe4         0.40
ZnO              3.44

In [69]:
data = [{'a': i, 'b': 2 * i} for i in range(3)] #From list of dicts
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [70]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

Exercise

Create a DataFrame from a two-dimensional NumPy
array of random numbers. Use column and index labels.

In [54]:
pd.DataFrame(np.random.rand(3,2), columns = ['foo', 'bar'], index=['a', 'b', 'c']) # Random values in a given shape.

foo       bar
a  0.933365  0.178208
b  0.633795  0.894692
c  0.322184  0.725407

Inspecting a dataframe

In [55]:
materials

bandgap is_metal
Hg0.7Cd0.3Te     0.35         
CuBr             3.08    False
LuP              1.30    False
Cu3SbSe4         0.40    False
ZnO              3.44    False

In [56]:
materials.head(3) #first 3

bandgap is_metal
Hg0.7Cd0.3Te     0.35         
CuBr             3.08    False
LuP              1.30    False

In [57]:
materials.tail(1) # last 1

bandgap is_metal
ZnO     3.44    False

In [58]:
materials.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Hg0.7Cd0.3Te to ZnO
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   bandgap   5 non-null      float64
 1   is_metal  5 non-null      object 
dtypes: float64(1), object(1)
memory usage: 292.0+ bytes


In [59]:
materials.describe()

bandgap
count  5.000000
mean   1.714000
std    1.466588
min    0.350000
25%    0.400000
50%    1.300000
75%    3.080000
max    3.440000

Index

In [73]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [61]:
ind[1]

3

In [62]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [63]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [64]:
ind[1] = 0 # index does not support mutable operations
ind

TypeError: Index does not support mutable operations

In [ ]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [ ]:
 indA & indB # Intersection

/var/folders/m8/v8_kdm011wg6m28tjk9k1lww0000gn/T/ipykernel_88103/1226259690.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB # Intersection


Int64Index([3, 5, 7], dtype='int64')

In [ ]:
indA | indB # Union

/var/folders/m8/v8_kdm011wg6m28tjk9k1lww0000gn/T/ipykernel_88103/621723989.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB # Union


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [ ]:
indA ^ indB # Symmetric difference

/var/folders/m8/v8_kdm011wg6m28tjk9k1lww0000gn/T/ipykernel_88103/1874724465.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^ indB # Symmetric difference


Int64Index([1, 2, 9, 11], dtype='int64')

Data indexing and selection, NumPy arrays

In [74]:
import numpy.random as rnd
arr = rnd.random((5,5))
arr

array([[0.94468451, 0.50207133, 0.93208228, 0.80675406, 0.17356866],
       [0.38565614, 0.36449287, 0.88095713, 0.98596363, 0.04865984],
       [0.68452953, 0.41650779, 0.32479174, 0.36620109, 0.50516088],
       [0.54522476, 0.23539136, 0.50995239, 0.3327931 , 0.61831621],
       [0.16672197, 0.52491568, 0.8341432 , 0.91560295, 0.40303485]])

In [75]:
arr[2, 1] # indexing

0.41650778743101613

In [76]:
arr[:, 1:2] # slicing

array([[0.50207133],
       [0.36449287],
       [0.41650779],
       [0.23539136],
       [0.52491568]])

In [78]:
arr[arr > 0.5] # masking

array([0.94468451, 0.50207133, 0.93208228, 0.80675406, 0.88095713,
       0.98596363, 0.68452953, 0.50516088, 0.54522476, 0.50995239,
       0.61831621, 0.52491568, 0.8341432 , 0.91560295])

In [79]:
 arr[0, [1, 2]] # fancy indexing

array([0.50207133, 0.93208228])

In [80]:
arr[:, [1, 2]] # combinations

array([[0.50207133, 0.93208228],
       [0.36449287, 0.88095713],
       [0.41650779, 0.32479174],
       [0.23539136, 0.50995239],
       [0.52491568, 0.8341432 ]])

Data selection in Series 

In [81]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [82]:
data['b']

0.5

In [84]:
'a' in data

True

In [ ]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [85]:
data.values()

TypeError: 'numpy.ndarray' object is not callable

In [87]:
data['a':'c'] # slicing by explicit index

a    0.25
b    0.50
c    0.75
dtype: float64

In [88]:
data[0:1] # slicing by implicit integer index, number of the row??

a    0.25
dtype: float64

In [89]:
data[(data > 0.3) & (data < 0.8)] # masking

b    0.50
c    0.75
dtype: float64

In [90]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [100]:
data[3] # explicit index (i.e., key) when indexing

'b'

In [92]:
data[1:3] # implicit index (i.e., position) when slicing, rows 

3    b
5    c
dtype: object

Data selection in Series (loc vs. iloc)

In [93]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [102]:
 data.loc[3] # loc - indexes, Index by key

'b'

In [109]:
data.loc[1:4]

1    a
3    b
dtype: object

In [110]:
data.iloc[1] #goes according rows, Index by array location

'b'

In [112]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [113]:
rng = np.random.default_rng(12345)
df = pd.DataFrame(rng.integers(0, 10, (3, 3)),columns=list('ABC'), index=list('ijk'))
df

A  B  C
i  6  2  7
j  3  2  7
k  6  6  9

In [114]:
df.values # NumPy array

array([[6, 2, 7],
       [3, 2, 7],
       [6, 6, 9]])

In [115]:
df.values[2] #row

array([6, 6, 9])

In [116]:
df.values[0,1]
#df.values[0][1] the same

2

In [117]:
df.iloc[0, 2]
#df.iloc[0][2] the same

7

In [118]:
df.loc['i']['A']
# df.loc['i', 'A'] is the same

6

In [119]:
df.loc[df.A > 3] # Checks element, prints row

A  B  C
i  6  2  7
k  6  6  9

In [120]:
df['A'] # Column

i    6
j    3
k    6
Name: A, dtype: int64

In [121]:
df['A'][1] # df['A'].iloc[1] is the same

3

In [122]:
df['i':'j']

A  B  C
i  6  2  7
j  3  2  7

In [123]:
df['i':'k']['A']

i    6
j    3
k    6
Name: A, dtype: int64

In [124]:
df['A']['i']

6

In [125]:
type(df['A']['i'])

numpy.int64

In [126]:
df['i':'i']['A']

i    6
Name: A, dtype: int64

In [127]:
type(df['i':'i']['A'])

pandas.core.series.Series

In [128]:
df['i']['A']

KeyError: 'i'

2 LECTURE

In [129]:
df = pd.read_csv("expt_gap.csv")
df.head()

Unnamed: 0       formula  gap expt
0           0  Hg0.7Cd0.3Te      0.35
1           1          CuBr      3.08
2           2           LuP      1.30
3           3      Cu3SbSe4      0.40
4           4           ZnO      3.44

In [130]:
df['gap expt'].idxmax()

2113

In [131]:
df.iloc[2113]

Unnamed: 0    2113
formula        LiF
gap expt      11.7
Name: 2113, dtype: object

In [132]:
df.iloc[df['gap expt'].idxmax()] #the same as two previous commands

Unnamed: 0    2113
formula        LiF
gap expt      11.7
Name: 2113, dtype: object

In [133]:
import numpy as np
rng = np.random.default_rng(12345)
rints=rng.integers(0,10,4)
pd.Series(rints)

0    6
1    2
2    7
3    3
dtype: int64

In [134]:
rng = np.random.default_rng(12345)
rints=rng.integers(0,10,(3,4))
df = pd.DataFrame(rints, columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  2  7  3
1  2  7  6  6
2  9  3  8  3

In [135]:
A = pd.Series([2, 4, 6], index=[0, 1, 2]) #складывается по индексам 
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [143]:
A.add(B, fill_value=0)

A     B    C
0   6.0  20.0  9.0
1  19.0  27.0  6.0
2   0.0   1.0  2.0

In [139]:
A = pd.DataFrame(rng.integers(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0   4  13
1  12  18

In [140]:
B = pd.DataFrame(rng.integers(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  7  2  9
1  9  7  6
2  1  0  2

In [141]:
A+B

A     B   C
0   6.0  20.0 NaN
1  19.0  27.0 NaN
2   NaN   NaN NaN

In [149]:
A.stack()

0  A     4
   B    13
1  A    12
   B    18
dtype: int64

In [148]:
fill = A.stack().mean()
fill

11.75

In [145]:
A.add(B, fill_value=fill)

A      B      C
0   6.00  20.00  20.75
1  19.00  27.00  17.75
2  11.75  12.75  13.75

Operations between DataFrame and Series

In [150]:
A = np.array([[3, 8, 2, 4], [2, 6, 4, 8], [6, 1, 3, 8]])
df = pd.DataFrame(A, columns=list('ijkl'))
df

i  j  k  l
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [151]:
df - df.iloc[1] # Default operation is row-wise

i  j  k  l
0  1  2 -2 -4
1  0  0  0  0
2  4 -5 -1  0

In [152]:
df - df.iloc[0][0] # Same as df - df.iloc[0, 0]

i  j  k  l
0  0  5 -1  1
1 -1  3  1  5
2  3 -2  0  5

In [155]:
df.subtract(df['i'], axis=0) # Operation can be column-wise

i  j  k  l
0  0  5 -1  1
1  0  4  2  6
2  0 -5 -3  2

In [156]:
df.subtract(df.iloc[2],axis=1)

i  j  k  l
0 -3  7 -1 -4
1 -4  5  1  0
2  0  0  0  0

In [157]:
half_row = df.iloc[0, ::2] #row 0, step = 2
half_row

i    3
k    2
Name: 0, dtype: int64

In [158]:
df - half_row # Remember: row-wise , минус 3 со столбика i, минус 2 со столбика k

i   j    k   l
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

In [159]:
df

i  j  k  l
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

 Handling missing data

In [160]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [161]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [166]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [163]:
vals2.sum()

nan

In [164]:
vals2.min()

nan

In [165]:
np.nansum(vals2)

8.0

In [167]:
np.nanmin(vals2)

1.0

In [168]:
np.nanmax(vals2)


4.0

Nan and None

In [169]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [173]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [174]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

Operating on null values

In [175]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [176]:
data.isnull() #Generate a Boolean mask indicaOng missing values

0    False
1     True
2    False
3     True
dtype: bool

In [177]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [178]:
data[data.notnull()] # Bool mask

0        1
2    hello
dtype: object

In [179]:
A = np.array([[3, None, 2, 4], [2, 6, np.nan, 8], [6, 1, 3, 8]])
df = pd.DataFrame(A, columns=list('ijkl'))
df

i     j    k  l
0  3  None    2  4
1  2     6  NaN  8
2  6     1    3  8

In [180]:
df.dropna(axis='columns', how='any') # any если хотя бы одно значение в столбике nan

i  l
0  3  4
1  2  8
2  6  8

In [181]:
df.dropna(axis='columns', how='all') # all если все значения в столбике nan

i     j    k  l
0  3  None    2  4
1  2     6  NaN  8
2  6     1    3  8

In [182]:
df.dropna(axis='rows', how='any')

i  j  k  l
2  6  1  3  8

In [183]:
data = pd.Series([1, np.nan, 2, None, 3],
                 index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [184]:
data.fillna(0) # Return a copy of the data with missing values filled or imputed

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [185]:
data.fillna(method='ffill')
# forward-fill


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [186]:
data.fillna(method='bfill')
# forward-fill

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

Simple aggregations(series)

In [187]:
ds = data.fillna(method='ffill')
dsd = ds.describe()
dsd
# forward-fill

count    5.00000
mean     1.80000
std      0.83666
min      1.00000
25%      1.00000
50%      2.00000
75%      2.00000
max      3.00000
dtype: float64

In [188]:
dsd['count']

5.0

groupby()

In [189]:
df = pd.DataFrame({'key':['A','B','C','A','B','C'], 'data':[1,2,3,4,5,6]})
df

key  data
0   A     1
1   B     2
2   C     3
3   A     4
4   B     5
5   C     6

In [190]:
df.groupby('key').sum()

data
key      
A       5
B       7
C       9

groupby

In [210]:
periodic_table = pd.read_csv("periodic_table_small.csv", encoding= 'unicode_escape')
periodic_table.head()

number       name symbol    name_symbol  \
0       1   Hydrogen      H    hydrogen, H   
1       2     Helium     He     helium, He   
2       3    Lithium     Li    lithium, Li   
3       4  Beryllium     Be  beryllium, Be   
4       5      Boron      B       boron, B   

                                          appearance  atomic_number  \
0                                      colorless gas              1   
1  colorless gas, exhibiting a red-orange glow wh...              2   
2                                      silvery-white              3   
3                                white-gray metallic              4   
4                                        black-brown              5   

                                group_block  period      element_category  \
0                          group 1, s-block       1     diatomic nonmetal   
1           group 18 (noble gases), s-block       1             noble gas   
2          group 1 (alkali metals), s-block       2          alkali metal   
3  group 2 (alkaline earth metals), s-block       2  alkaline earth metal   
4                         group 13, p-block       2             metalloid   

   atomic_weight  ... Unnamed: 15  boiling_point density_at_stp  \
0       1.008000  ...    7.470000         20.271        0.08988   
1       4.002602  ...         NaN          4.222        0.17860   
2       6.940000  ...  651.171429           1603            NaN   
3       9.012183  ...         NaN           2742            NaN   
4      10.810000  ...         NaN           4200            NaN   

  when_liquid_at_mp when_liquid_at_bp  triple_point critical_point  \
0             0.070           0.07099       13.8033        32.9380   
1             0.145           0.12500        2.1770         5.1953   
2             0.512               NaN           NaN      3220.0000   
3             1.690               NaN           NaN      5205.0000   
4               NaN               NaN           NaN            NaN   

                                 ionization_energies  covalent_radius  \
0                                 1st: 1312.0 kJ/mol          31±5 pm   
1             1st: 2372.3 kJ/mol, 2nd: 5250.5 kJ/mol               28   
2  1st: 520.2 kJ/mol, 2nd: 7298.1 kJ/mol, 3rd: 11...         128±7 pm   
3  1st: 899.5 kJ/mol, 2nd: 1757.1 kJ/mol, 3rd: 14...          96±3 pm   
4  1st: 800.6 kJ/mol, 2nd: 2427.1 kJ/mol, 3rd: 36...          84±3 pm   

   van_der_waals_radius  
0                 120.0  
1                 140.0  
2                 182.0  
3                 153.0  
4                 192.0  

[5 rows x 25 columns]

In [212]:
period_meltpoint = periodic_table.groupby('period')['van_der_waals_radius'].mean()
period_meltpoint.head()

period
1    130.000000
2    161.625000
3    189.625000
4    193.250000
5    207.363636
Name: van_der_waals_radius, dtype: float64

In [213]:
periodic_table.groupby('period')['van_der_waals_radius'].agg([min, max, sum])

min    max     sum
period                      
1       120.0  140.0   260.0
2       135.0  192.0  1293.0
3       173.0  227.0  1517.0
4       139.0  275.0  2319.0
5       158.0  303.0  2281.0
6       155.0  343.0  2331.0
7       186.0  348.0   817.0

In [214]:
periodic_table.groupby(['period', 'phase'])['van_der_waals_radius'].mean()

period  phase            
1       gas                  130.000000
2       gas                  149.000000
        solid                174.250000
3       gas                  181.500000
        solid                192.333333
4       gas                  202.000000
        liquid               185.000000
        solid                193.200000
5       gas                  216.000000
        solid                206.500000
6       gas                  220.000000
        liquid               155.000000
        solid                217.333333
7       gas (predicted)             NaN
        solid                234.500000
        solid (predicted)           NaN
        solid presumably     348.000000
Name: van_der_waals_radius, dtype: float64

In [221]:
periodic_table.groupby(['period', 'phase'])['van_der_waals_radius', 'atomic_number'].mean()

/var/folders/m8/v8_kdm011wg6m28tjk9k1lww0000gn/T/ipykernel_68026/1974521221.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  periodic_table.groupby(['period', 'phase'])['van_der_waals_radius', 'atomic_number'].mean()


van_der_waals_radius  atomic_number
period phase                                                 
1      gas                          130.000000       1.500000
2      gas                          149.000000       8.500000
       solid                        174.250000       4.500000
3      gas                          181.500000      17.500000
       solid                        192.333333      13.500000
4      gas                          202.000000      36.000000
       liquid                       185.000000      35.000000
       solid                        193.200000      26.500000
5      gas                          216.000000      54.000000
       solid                        206.500000      45.062500
6      gas                          220.000000      86.000000
       liquid                       155.000000      80.000000
       solid                        217.333333      69.666667
7      gas (predicted)                     NaN     112.000000
       solid                        234.500000      93.500000
       solid (predicted)                   NaN     109.117647
       solid presumably             348.000000      87.000000

pivot_table

In [224]:
periodic_table.pivot_table(values='van_der_waals_radius', index='period',aggfunc=[np.mean, np.std], fill_value=0.0)

mean                  std
       van_der_waals_radius van_der_waals_radius
period                                          
1                130.000000            14.142136
2                161.625000            18.461833
3                189.625000            18.980723
4                193.250000            37.772344
5                207.363636            41.231718
6                211.909091            52.726567
7                272.333333            81.525047

In [225]:
periodic_table.pivot_table(values='van_der_waals_radius', index='period')

van_der_waals_radius
period                      
1                 130.000000
2                 161.625000
3                 189.625000
4                 193.250000
5                 207.363636
6                 211.909091
7                 272.333333

In [226]:
periodic_table.pivot_table(values='van_der_waals_radius', index='period', columns='phase', fill_value=0.0, margins=True)

phase          gas  liquid       solid  solid presumably         All
period                                                              
1       130.000000       0    0.000000                 0  130.000000
2       149.000000       0  174.250000                 0  161.625000
3       181.500000       0  192.333333                 0  189.625000
4       202.000000     185  193.200000                 0  193.250000
5       216.000000       0  206.500000                 0  207.363636
6       220.000000     155  217.333333                 0  211.909091
7         0.000000       0  234.500000               348  272.333333
All     168.818182     170  201.780488               348  196.690909

In [228]:
pt = periodic_table.pivot_table(values=['van_der_waals_radius', 'atomic_number'], index='period', columns='phase', aggfunc={'van_der_waals_radius':np.min, 'atomic_number':np.max}, fill_value=0.0)
pt

atomic_number                                                 \
phase            gas gas (predicted) liquid solid solid (predicted)   
period                                                                
1                  2               0      0     0                 0   
2                 10               0      0     6                 0   
3                 18               0      0    16                 0   
4                 36               0     35    34                 0   
5                 54               0      0    53                 0   
6                 86               0     80    85                 0   
7                  0             112      0    99               118   

                        van_der_waals_radius                               \
phase  solid presumably                  gas gas (predicted) liquid solid   
period                                                                      
1                     0                  120               0      0     0   
2                     0                  135               0      0   153   
3                     0                  175               0      0   173   
4                     0                  202               0    185   139   
5                     0                  216               0      0   158   
6                     0                  220               0    155   166   
7                    87                    0               0      0   186   

                                           
phase  solid (predicted) solid presumably  
period                                     
1                      0                0  
2                      0                0  
3                      0                0  
4                      0                0  
5                      0                0  
6                      0                0  
7                      0              348

In [229]:
pt.to_csv('periodic_table_melt_boil.csv')
