USING LIBRARIES

In [705]:
import math as m
l0 = [n for n in range (-5, 5)]
print(l0)
print(l0[0], l0[-2])
print(len(l0))

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]
-5 3
10


In [706]:
#l1 = sorted ([l0[i]*m.pi/10 for i in l0])
lst_index = [index for index in range(len(l0))]
lst_items = [i for i in l0]
print(f"My Way: {lst_index} \n Dan's Way {lst_items}")

l1 = [item*m.pi/10 for item in l0]
l1

My Way: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 Dan's Way [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


[-1.5707963267948966,
 -1.2566370614359172,
 -0.9424777960769379,
 -0.6283185307179586,
 -0.3141592653589793,
 0.0,
 0.3141592653589793,
 0.6283185307179586,
 0.9424777960769379,
 1.2566370614359172]

In [707]:
l2= [m.sin(n) for n in l1]
l2

[-1.0,
 -0.9510565162951535,
 -0.8090169943749473,
 -0.5877852522924731,
 -0.3090169943749474,
 0.0,
 0.3090169943749474,
 0.5877852522924731,
 0.8090169943749473,
 0.9510565162951535]

RDKit - chemical libraries 

NumPy

Generate NumPy array from tuple

In [708]:
import numpy as np
a = np.array((1, 2, 3, 4), float) # float - после запятой (64 bites), numpy_float_125 если нужно больше, чем 64 bites 
a

array([1., 2., 3., 4.])

Generate NumPy array from list

In [709]:
list1 = [[1,2,3], [4,5,6]] # матрица, элемент [1,0] = 4
print(list1)
mat = np.array(list1, complex) #complex - комплексное число 
mat

[[1, 2, 3], [4, 5, 6]]


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

Properties

In [710]:
mat.shape # 2 строки, 3 столбика

(2, 3)

In [711]:
mat.size #6 элементов

6

In [712]:
mat.ndim #2 dimensional array

2

In [713]:
type(mat) #показывает тип - матрица 

numpy.ndarray

In [714]:
mat.dtype

dtype('complex128')

In [715]:
list1 = [[1,2,3], [4,5,6]] 
mat = np.array(list1, float)
complex_size = mat.itemsize #размер каждого элемента
print(complex_size)

8


In [716]:
import numpy as np
a = np.array(((1,2,3),(4,5,6),(7,8,9)), float) #Generate NumPy array from list
a
# a[2,0] для одного элемента 

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [717]:
a=np.arange(10) # l1 =list(range(10)) в обычном питоне 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [718]:
b=np.arange(0.1, 0.2, 0.02) #от 0.1 до 0.2 с шагом 0.02
b

array([0.1 , 0.12, 0.14, 0.16, 0.18])

In [719]:
c = np.linspace(-np.pi, np.pi, 10) # создаёт 10 чисел, сам считает шаг
c

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [720]:
a = np.zeros((4, 6), float)
a
#a.shape

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [721]:
b = np.ones((2, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [722]:
c = np.full((2, 3), 11.1) #11.1 числа, которыми будет заполнена матрица 
c

array([[11.1, 11.1, 11.1],
       [11.1, 11.1, 11.1]])

In [723]:
d = np.empty((3,3)) # не очень поняла 
d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [724]:
a = np.zeros((4, 6), float)
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [725]:
b = np.empty_like(a) #сохраняется shape матрицы a (4,6)
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [726]:
c = np.ones_like(a) #сохраняется shape матрицы a (4,6)
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [727]:
d = np.full_like(a, 9999.0) #сохраняется shape матрицы a (4,6), но заполняется 9999.0 
d

array([[9999., 9999., 9999., 9999., 9999., 9999.],
       [9999., 9999., 9999., 9999., 9999., 9999.],
       [9999., 9999., 9999., 9999., 9999., 9999.],
       [9999., 9999., 9999., 9999., 9999., 9999.]])

In [728]:
a = np.array(['foo', 'foo-bar'])
a

array(['foo', 'foo-bar'], dtype='<U7')

In [729]:
dna = 'AAAGTCTGAC' #????
a = np.array(dna, dtype='c')
a

array([b'A', b'A', b'A', b'G', b'T', b'C', b'T', b'G', b'A', b'C'],
      dtype='|S1')

Slicing

In [730]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [731]:
a[-2]

8

In [732]:
a[1:3] = -1
a

array([ 0, -1, -1,  3,  4,  5,  6,  7,  8,  9])

In [733]:
a[1:7:2] #Slicing with x[start:stop:step]

array([-1,  3,  5])

In [734]:
import numpy as np
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [735]:
mat[1,-2]

5

In [736]:
a = np.zeros((4, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [737]:
#Slicing of arrays in multiple dimensions
a[1:3, 1:3] = 10.0
a

array([[ 0.,  0.,  0.,  0.],
       [ 0., 10., 10.,  0.],
       [ 0., 10., 10.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [738]:
a = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
a

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [739]:
a[:2, :3] # Union of 2 rows, 3 columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [740]:
a[:3, :2] # Union of 3 rows, 2 columns


array([[12,  5],
       [ 7,  6],
       [ 1,  6]])

In [741]:
a[:2, ::2] # 2 rows, every other column

array([[12,  2],
       [ 7,  8]])

In [742]:
a[::-1, ::-1] # Transpose matrix

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Exercises

In [743]:
a = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
a

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [744]:
a[:3:2, :3:2]

array([[12,  2],
       [ 1,  7]])

In [745]:
a[:3:2, :4:3]

array([[12,  4],
       [ 1,  7]])

In [746]:
a[np.arange(3), np.arange(3)] #[0,1,2] [0,1,2] ???

array([12,  6,  7])

In [747]:
a = np.arange(10)
b = a # reference, changing values in b changes a
c = a.copy() #true copy
d = a[1:4]
d[0] = 9999.0
print(d)
print(c)
print(a)

[9999    2    3]
[0 1 2 3 4 5 6 7 8 9]
[   0 9999    2    3    4    5    6    7    8    9]


In [748]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat


array([[1, 2, 3],
       [4, 5, 6]])

In [749]:
mat.reshape(3, 2) # 1, 2 first raw; 3,4 second raw; 5,6 third raw

array([[1, 2],
       [3, 4],
       [5, 6]])

In [750]:
mat = np.arange(1, 10)
mat.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [751]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ravel() #flatten array to 1D

array([1, 2, 3, 4, 5, 6])

In [752]:
mat1 = np.array([1, 2, 3])
mat2 = np.array([4, 5, 6])
np.hstack([mat1, mat2]) # stack arrays on top of one another

array([1, 2, 3, 4, 5, 6])

In [753]:
np.vstack([mat1, mat2]) # stack arrays on top of one another

array([[1, 2, 3],
       [4, 5, 6]])

In [754]:
mat1 = np.array([[1, 2, 3], [4, 5, 6]]) # 2×3 array
mat2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate((mat1, mat2)) # same effect as vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [755]:
mat3 = np.concatenate((mat1, mat2))
mat3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [756]:
np.concatenate((mat1, mat2), axis=1) # 2×6 array, same effect as hstack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [757]:
np.split(mat3, 3, axis=1) # Splitting vertical, because axis=1, 3-на сколько порезать нужно

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [758]:
np.split(mat3, 2, axis=0) # Splitting gorizontally!!!

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [759]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [760]:
a + b #broadcasting

array([3., 4., 5.])

In [761]:
a * a

array([1., 4., 9.])

In [762]:
a ** b

array([1., 4., 9.])

In [763]:
import numpy as np, math
a = np.linspace(-math.pi, math.pi, 8)
a

array([-3.14159265, -2.24399475, -1.34639685, -0.44879895,  0.44879895,
        1.34639685,  2.24399475,  3.14159265])

In [764]:
np.sin(a)

array([-1.22464680e-16, -7.81831482e-01, -9.74927912e-01, -4.33883739e-01,
        4.33883739e-01,  9.74927912e-01,  7.81831482e-01,  1.22464680e-16])

In [765]:
import numpy as math
math.sin(a)

array([-1.22464680e-16, -7.81831482e-01, -9.74927912e-01, -4.33883739e-01,
        4.33883739e-01,  9.74927912e-01,  7.81831482e-01,  1.22464680e-16])

In [766]:
x = np.array([1, 2, 3, 4, 5])
x < 3

array([ True,  True, False, False, False])

In [767]:
x > 3

array([False, False, False,  True,  True])

In [768]:
x <= 3

array([ True,  True,  True, False, False])

In [769]:
x != 3

array([ True,  True, False,  True,  True])

In [770]:
x = np.array([[5, 0, 3, 3], [7, 9, 3, 5], [2, 4, 7, 6]])
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [771]:
 x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [772]:
np.count_nonzero(x < 6) # How many values less than 6

8

In [773]:
np.sum(x < 6)

8

In [774]:
np.sum(x < 6, axis=1) # how many true in raw

array([4, 2, 2])

In [775]:
np.sum(x < 6, axis=0) # how many true in columns

array([2, 2, 2, 2])

In [776]:
np.sum(x) #сумма всех элементов в матрице

54

In [777]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [778]:
(x > 2.5) & (x < 7.5) # & and

array([False, False,  True,  True,  True,  True,  True, False, False,
       False])

In [779]:
np.sum((x > 2.5) & (x < 7.5)) # 5 items TRUE

5

In [780]:
(x <= 2.5) | (x >= 7.5) # | or или

array([ True,  True, False, False, False, False, False,  True,  True,
        True])

In [781]:
~( (x <= 2.5) | (x >= 7.5) )

array([False, False,  True,  True,  True,  True,  True, False, False,
       False])

In [782]:
np.sum(~( (x <= 2.5) | (x >= 7.5) )) ## 5 items TRUE

5

I/O with NumPy

In [783]:
import numpy as np
x = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], np.int32)
np.savetxt("test.txt", x) # Inspect the file in a viewer

In [784]:
np.savetxt("test2.txt", x, fmt="%2.3f", delimiter=",")

In [785]:
np.savetxt("test3.txt", x, fmt="%04d", delimiter=" :-) ")

In [786]:
y = np.loadtxt("test.txt")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [787]:
y = np.loadtxt("test2.txt", delimiter=",")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [788]:
y = np.loadtxt("test3.txt", delimiter=" :-) ")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [789]:
y = np.loadtxt("test3.txt", delimiter=" :-) ", usecols=(0,1))
print(y)

[[1. 2.]
 [4. 5.]
 [7. 8.]]


Random numbers

In [790]:
import numpy.random as rnd
rnd.random((2,2)) # Random numbers in range [0, 1]

array([[0.97978654, 0.37977877],
       [0.94630267, 0.92983715]])

In [791]:
rnd.choice(np.arange(4)) # Random number in range [0, 3]

2

In [792]:
rnd.choice(np.arange(4), 10) # 10 random numbers

array([1, 1, 3, 2, 3, 1, 0, 2, 1, 0])

In [793]:
a = rnd.choice(np.arange(100),100) #random numbers exercise
a

array([12, 86, 79, 49, 39, 73, 76, 10, 84, 35, 49, 72, 66, 26, 71, 64, 26,
       94, 92,  0, 59, 33, 16,  6, 27,  7, 10, 96, 21,  7, 56, 28, 64, 68,
       38, 50, 73, 73,  3, 71, 65,  0, 11, 48,  5, 85, 49, 20, 95, 36, 59,
       27, 51, 24, 48, 95, 37, 31, 77, 68, 72, 63, 14, 13, 56, 43, 54, 35,
       97, 41, 10, 52, 93, 10, 16, 38, 32, 45, 83, 59, 41, 41, 10, 48, 12,
       44, 71, 25, 80, 30, 35, 76, 42, 33, 35, 55, 46, 96, 37,  4])

Polynomials

In [794]:
x = np.linspace(-4, 4, 7) #7 random numbers from -4 to 4
x

array([-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
        2.66666667,  4.        ])

In [834]:
y = x**2 + rnd.random(x.shape) #x.shape - tuple - array of random numbers, match shape of x
y

array([ 4.25220334,  1.01807499, 16.96137711,  9.79800708, 25.64910443])

In [833]:
p = np.polyfit(x, y, 2) # Fit parabola, ax2+bx+c, выводит a,b,c
p

array([0.9116885 , 0.3547988 , 0.57902327])

  Linear algebra

In [797]:
A = np.array(((2, 1), (1, 3)))
B = np.array(((-2, 4.2), (4.2, 6)))
A

array([[2, 1],
       [1, 3]])

In [798]:
B

array([[-2. ,  4.2],
       [ 4.2,  6. ]])

In [799]:
C = np.dot(A, B) # [[2*-2+1*4,2 ; 2*4,2+1*6], [1*-2+3*4,2 ; 1*4,2 + 3*6]]
C

array([[ 0.2, 14.4],
       [10.6, 22.2]])

In [800]:
b= np.array((1, 2)) # vektor
b

array([1, 2])

In [801]:
np.linalg.solve(C, b) # solve (C)(X) = (b), gives X matrix

array([0.04453441, 0.06882591])

In [802]:
H = np.array(((10., 0.5), (0.5, 13.1)))
H

array([[10. ,  0.5],
       [ 0.5, 13.1]])

In [835]:
np.linalg.eig(H) # first array E, second one A

(array([ 9.92135025, 13.17864975]),
 array([[-0.98785338, -0.15538884],
        [ 0.15538884, -0.98785338]]))

 Advanced "fancy" indexing


In [841]:
x = np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [842]:
x[3]

7

In [843]:
x[np.array([3, 3, 1, 8])] # x[[3, 3, 1, 8]] does the same
#вызываем индексы элементов

array([7, 7, 9, 2])

In [844]:
x[[3, 3, 1, 8]]

array([7, 7, 9, 2])

In [845]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [846]:
m = x > 7
m

array([ True,  True,  True, False, False, False, False, False, False])

In [847]:
x[m]

array([10,  9,  8])

 Vectorized operations
 for loops in Python are slow
• Use "vectorized" operations when possible


In [2]:
# brute force using a for loop
import numpy as np
arr = np.arange(1000)
dif = np.zeros(999, int)
for i in range(1, len(arr)):
    dif[i-1] = arr[i] - arr[i-1]
dif

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [3]:
# vectorized operation - faster
arr = np.arange(1000)
dif = arr[1:] - arr[:-1]
dif

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

 Broadcasting

In [852]:
from numpy import array
np.arange(3) + 5

array([5, 6, 7])

In [853]:
a = array([[1,2],[3,4],[5,6]], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [854]:
b = array([[7,11]], float)
b

array([[ 7., 11.]])

In [855]:
a*b

array([[ 7., 22.],
       [21., 44.],
       [35., 66.]])

In [4]:
a = np.arange(5).reshape(5, 1)
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [5]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [6]:
c=  a + b # different shape, expand two matrix
c #matrix b - amount of columns, a - amount of raws

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [865]:
# Example: calculate distances from a given point • Try with fewer points and print intermediate values!array containing 3d coordinates for 100 points
points = np.random.random((100, 3))
origin = np.array((1.0, 2.2, -2.2))
dists = (points - origin)**2
dists

array([[4.22227627e-01, 2.93689203e+00, 7.13012220e+00],
       [1.72124177e-01, 4.25316673e+00, 8.04016777e+00],
       [6.18582786e-02, 2.65519329e+00, 7.56415523e+00],
       [3.04830659e-01, 2.84762796e+00, 6.74963433e+00],
       [4.58213827e-03, 2.40592773e+00, 9.93859799e+00],
       [4.65554997e-01, 2.76822502e+00, 8.26816213e+00],
       [9.81090071e-01, 1.47492562e+00, 6.80826085e+00],
       [5.37163422e-01, 1.57905779e+00, 9.58278121e+00],
       [7.26249560e-01, 4.05947934e+00, 9.64000490e+00],
       [2.28056643e-01, 1.51751694e+00, 6.35832676e+00],
       [1.13317595e-01, 1.72135458e+00, 6.92114854e+00],
       [3.34344798e-02, 3.50057301e+00, 9.73499631e+00],
       [9.73981806e-03, 4.20727271e+00, 6.07507965e+00],
       [1.22892072e-02, 4.59373292e+00, 6.33091774e+00],
       [3.95349687e-01, 4.58833610e+00, 6.69740144e+00],
       [2.10350703e-03, 2.39363923e+00, 6.22411397e+00],
       [1.22893372e-01, 2.80510125e+00, 7.85425410e+00],
       [9.69993057e-01, 2.01432

In [870]:
dists = np.sqrt(np.sum(dists, axis=1)) #axis = 1 суммы по строкам
dists

array([3.23870991, 3.53064564, 3.2064321 , 3.14675912, 3.51412974,
       3.39145133, 3.04372741, 3.42038045, 3.7981224 , 2.84673503,
       2.95902361, 3.64266438, 3.20812908, 3.30710445, 3.41776056,
       2.93595925, 3.28363346, 3.4072085 , 3.70074798, 3.34494893,
       3.63345763, 3.63677057, 2.83350372, 3.41067395, 3.10190112,
       3.03943944, 2.91406235, 3.09239678, 3.28358117, 3.08056923,
       2.93162381, 2.59271808, 3.86514577, 3.20953561, 3.22538649,
       3.15021943, 3.38011824, 3.49071583, 3.07192574, 3.4150185 ,
       3.59162695, 3.5247321 , 2.99070665, 3.70154356, 3.55827017,
       3.4633247 , 3.34928252, 3.10289783, 3.62131642, 3.1374467 ,
       3.50101149, 3.05892201, 3.3652093 , 3.18909254, 2.8615782 ,
       3.35876465, 2.86395303, 3.19562619, 3.82477593, 3.22569322,
       3.64786328, 2.75147803, 2.66144133, 3.71139047, 3.36632067,
       3.27058762, 3.49060043, 2.75720334, 2.97557077, 3.05187829,
       2.99603004, 3.44197039, 2.82175392, 3.72326786, 3.18401

In [874]:
# find the most distant point
i = np.argmax(dists) # index of the biggest value
print(points[i]) #value of points list

[0.06266443 0.01245177 0.84555194]


 Sorting

In [875]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x) # x was changed

array([1, 2, 3, 4, 5])

In [824]:
x

array([2, 1, 4, 3, 5])

In [877]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [878]:
x.sort() # x was changed
x

array([1, 2, 3, 4, 5])

In [879]:
x

array([1, 2, 3, 4, 5])

In [880]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x) # sort arguments
print(i)

[1 0 3 2 4]
